[variables]
DOTNET_ROOT = "/nix/store"

[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
    "dotnet restore EcommerceAPI.csproj",
    "dotnet build EcommerceAPI.csproj -c Release --no-restore",
    "dotnet publish EcommerceAPI.csproj -c Release -o out --no-restore /p:UseAppHost=false"
]

[phases.start]
cmd = "dotnet out/EcommerceAPI.dll"

[staticAssets]
dir = "wwwroot"
